### ISSUE TITLE
get_autocorr_time breaks from 2.1 to 2.2

### ISSUE THREAD

**Issue by astronomeralex** [dfm/emcee#186]
my code that uses emcee worked perfectly with emcee 2.1.0, but when I upgraded to 2.20, I get this error in the autocorrelation calculation

```
Traceback (most recent call last):
  File "01main.py", line 220, in <module>
    dataAvgFluxErr)  
  File "/gpfs/home/apm5587/MCSED/dust/src/emcee_functions.py", line 246, in conductMCMC
    sampler.get_autocorr_time(), 
  File "/storage/home/apm5587/.local/lib/python2.7/site-packages/emcee/ensemble.py", line 489, in get_autocorr_time
    window=window, fast=fast)
TypeError: integrated_time() got an unexpected keyword argument 'window'
```

seems like there were some changes to function keywords that didn't get propagated through the functions that call them?
