### PR TITLE
Fix calls of integrated_time

### LINKED ISSUE #186: get_autocorr_time breaks from 2.1 to 2.2
my code that uses emcee worked perfectly with emcee 2.1.0, but when I upgraded to 2.20, I get this error in the autocorrelation calculation

```
Traceback (most recent call last):
  File "01main.py", line 220, in <module>
    dataAvgFluxErr)  
  File "/gpfs/home/apm5587/MCSED/dust/src/emcee_functions.py", line 246, in conductMCMC
    sampler.get_autocorr_time(), 
  File "/storage/home/apm5587/.local/lib/python2.7/site-packages/emcee/ensemble.py", line 489, in get_autocorr_time
    window=window, fast=fast)
TypeError: integrated_time() got an unexpected keyword argument 'window'
```

seems like there were some changes to function keywords that didn't get propagated through the functions that call them?

### PR DESCRIPTION
**Pull request by terhardt**
Fixed the calls to `integrated_time` in MH and Ensemble samplers.

This fixes #186 and #187

### CODE REVIEW

**Comment by terhardt** [comment]
The test for the autocorrelation time seems to be able to fail randomly. I've tried this several times on my machine without the test failing.
Probably one of the walkers gets stuck, increasing the autocorrelation time.

**Comment by dfm** [comment]
Jeez... I'm an idiot. Thanks for this! 🍻 

I've also fixed the seed in the tests – should have done that ages ago. Hopefully that fixes the issue!
